FitOn/urls.py
from django.contrib import admin
from django.urls import path, include
from metrics.views import get_metric_data
from user.views import loginView

urlpatterns = [
    path("", loginView),
    path("admin/", admin.site.urls),
    path("metrics/", include("metrics.urls")),
    path("user/", include("user.urls")),
    path("exercise/", include("exercise.urls")),
]

exercise/urls.py
from django.urls import path
from exercise import views

app_name="exercise"
urlpatterns = [
    path('list/', views.list_exercises, name='list_exercises'),
    path('store/', views.store_exercises, name='store_exercises'),
]

user/urls.py
from django.urls import path
from . import views
from metrics.views import get_metric_data

app_name="user"
urlpatterns = [
    path('callback/', views.callback_google_fit, name='callback_google_fit'),
    path('authorize/', views.authorize_google_fit, name='authorize_google_fit'),
    path('home/', get_metric_data, name='home_dashboard'),
    path('account/', views.account_page, name='account'),
    path("registration/", views.register, name="user_registration"),
    path("login/", views.loginView, name="login"),
    path("passwordReset/", views.passwordResetView, name="passwordReset"),
    path("logout/", views.logoutView, name="logout"),
    path(
        "passwordResetConfirm/<uidb64>/<token>",
        views.passwordResetConfirmView,
        name="passwordResetConfirm",
    ),
]

user/models.py
from django.db import models

class Choices:
    sex = [
        ("male", "Male"),
        ("female", "Female"),
        ("other", "Other"),
    ]
    
class User(models.Model):
    name = models.CharField(max_length=100, default="Default Name")
    email = models.EmailField(default="example@example.com", unique=True)
    phone = models.CharField(max_length=15, default="000-000-0000")
    sex = models.CharField(max_length=10, choices=Choices.sex, default="other")
    height = models.FloatField(max_length=100)
    weight = models.FloatField(max_length=100)
    city = models.CharField(max_length=50)
    avatar = models.ImageField(
        upload_to="avatars/",
        default="avatars/default-avatar.png",
        null=True,
        blank=True,
    )
    
    def __str__(self):
        return self.name + " (" + self.email + ")"

user/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from google_auth_oauthlib.flow import Flow
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.contrib.auth.models import User as  DjangoUser
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.template.loader import render_to_string
from user.models import Choices, User
from django.conf import settings
import re
import boto3

SCOPES = [
    'https://www.googleapis.com/auth/fitness.activity.read', 
    'https://www.googleapis.com/auth/fitness.body.read', 
    'https://www.googleapis.com/auth/fitness.heart_rate.read', 
    'https://www.googleapis.com/auth/fitness.sleep.read',
    'https://www.googleapis.com/auth/fitness.blood_glucose.read',
    'https://www.googleapis.com/auth/fitness.blood_pressure.read',
    'https://www.googleapis.com/auth/fitness.body_temperature.read',
    'https://www.googleapis.com/auth/fitness.location.read',
    'https://www.googleapis.com/auth/fitness.nutrition.read',
    'https://www.googleapis.com/auth/fitness.oxygen_saturation.read',
    'https://www.googleapis.com/auth/fitness.reproductive_health.read'
]

PASSWORD_RESET_SUBJECT = "FitOn Account Password Reset Request"



def home_dashboard(request):
    return render(request, 'user/dashboard.html')

def logoutView(request):
    logout(request)
    return redirect("user:home_dashboard")

def loginView(request):
    if request.method == "POST":
        username = request.POST.get("user_email")
        password = request.POST.get("user_pwd")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            print("Login successful")
            return redirect("user:account")  # Redirect to the home page after login

        else:
            messages.error(request, "Incorrect Credentials! User does not exist!")
            return redirect("user:login")
    template_name = "user/login.html"
    return render(request, template_name)

def user_exists(email):
    return User.objects.filter(email=email).exists()

def create_django_user(email, password, name):
    usr = DjangoUser.objects.create_user(email, email, password)
    usr.first_name = name
    usr.save()
    return usr

def create_user_profile(**kwargs):
    filtered_kwargs = {k: v for k, v in kwargs.items()}
    User.objects.create(**filtered_kwargs)

def register(request):
    if request.method == "POST":
        # Collecting data from the form
        form_data = get_form_data(request)
        if type(form_data) is str:
            messages.error(request, form_data)
            return HttpResponseRedirect(reverse("user:user_registration"))
        if user_exists(form_data["email"]):
            messages.error(request, "User already exists! Please go to login page.")
            return HttpResponseRedirect(reverse("user:user_registration"))
        # try:
        usr = create_django_user(
            form_data["email"], form_data["password"], form_data["name"]
        )
        pwd = form_data["password"]
        del form_data["password"]
        create_user_profile(**form_data)
        login(request, usr)
        print("User saved successfully")
        client = boto3.client('cognito-idp', region_name='us-east-1')
        
        response = client.sign_up(
            ClientId='48c6righn4ev7j9pqksehr4f1o',
            Username=form_data["email"],
            Password=pwd,
            UserAttributes=[
                {
                    'Name': 'custom:city',
                    'Value': form_data["city"]
                },
                {
                    'Name': 'custom:height',
                    'Value': form_data["height"]
                },
                {
                    'Name': 'custom:phone',
                    'Value': form_data["phone"]
                },
                {
                    'Name': 'custom:weight',
                    'Value': form_data["weight"]
                },
                # Add more attributes as needed
            ]
        )
        
        print(response)
            
        # except Exception as e:
        #     messages.error(
        #         request,
        #         "Failed to add new user! Invalid details / User already exists.",
        #     )
        #     print(e)
        #     return render(request, template_name="user/user_registration.html")

        return HttpResponseRedirect(
            reverse("user:account")
        )  # redirect to home page after successful registration
    
    else:
        return render(
            request, template_name="user/user_registration.html"
        )

def get_form_data(request):  # noqa: C901
    # Collecting data from the form
    name = request.POST.get("user_name") or None
    email = request.POST.get("user_email") or None
    phone = request.POST.get("user_phone") or None
    sex = request.POST.get("user_sex") or None
    password = request.POST.get("password") or None
    city = request.POST.get("city") or None
    height = request.POST.get("height") or None
    height_inches = request.POST.get("inches") or None
    height_unit = request.POST.get("height_unit") or None
    weight_unit = request.POST.get("weight_unit") or None
    weight = request.POST.get("weight") or None
    
    if (not height_unit) or (not weight_unit):
        return "Error: Invalid Units"
    
    if weight_unit == "lb" and weight is not None:
        weight = float(weight) * 0.453592 #Convert to kg
    
    if height_unit == "ft_in" and height is not None:
        #Convert to cm
        height = float(height) * 30.48
        if height_inches:
            height += float(height_inches) * 2.54

    form_data = {
        "name": name,
        "email": email,
        "phone": phone,
        "sex": sex,
        "password": password,
        "city": city,
        "weight": weight,
        "height": height
    }

    if not isValidPassword(password):
        return "Error: Invalid Password"

    ret, msg = check_user_validity(form_data)

    if not ret:
        return msg

    return form_data

def isValidEmail(email):
    if not email:
        return False
    if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
        return False
    return True

def check_user_validity(form_data):  # noqa: C901
    try:
        if not form_data["name"]:
            return False, "Error: Invalid Name"
        if not isValidEmail(form_data["email"]):
            return False, "Error: Invalid Email"
        if not form_data["phone"]:
            return False, "Error: Invalid Phone"
        if form_data["sex"] not in [opt[0] for opt in Choices.sex]:
            return False, "Error: Invalid Sex"
        if not form_data["city"]:
            return False, "Invalid City"
        if not form_data["city"]:
            return False, "Invalid City"
        if not form_data["height"]:
            return False, "Invalid Height"
        if not form_data["weight"]:
            return False, "Invalid Weight"

        return True, ""

    except Exception as e:
        print(e)
        return False, "Invalid User Details"

def passwordResetView(request):
    template_name = "user/resetPassword/password_reset.html"

    if request.method == "GET":
        return render(request, template_name)

    else:
        user_email = request.POST.get("user_email")
        if send_email(
            request,
            user_email,
            "user/resetPassword/template_reset_password.html",
            PASSWORD_RESET_SUBJECT,
        ):
            alert_message = "Email sent. Please follow the link to reset your password."
            messages.success(request, alert_message)
            return HttpResponseRedirect(reverse("user:login"))
        else:
            alert_message = (
                "Email not exists in our database. Please register a new account."
            )
            messages.error(request, alert_message)
            return HttpResponseRedirect(reverse("user:user_registration"))

def isValidPassword(password):
    if not password:
        return False
    if not len(password) >= 8:
        return False
    return True

def send_email(request, user_email, email_template, subject, **kwargs):
    try:
        user = User.objects.get(email=user_email)
        token_generator = PasswordResetTokenGenerator()
        context = kwargs
        context["user"] = user
        context["domain"] = get_current_site(request).domain
        context["uid"] = urlsafe_base64_encode(user.email.encode("utf-8"))
        context["token"] = token_generator.make_token(user)
        context["protocol"] = "https" if request.is_secure() else "http"
        message = render_to_string(
            email_template,
            context,
        )
        email = EmailMessage(subject, message, to=[user.email])
        if email.send():
            return True
        else:
            return False
    except Exception as e:
        print(e)
        return False

def passwordResetConfirmView(request, uidb64, token):
    template_name = "user/resetPassword/password_reset_confirm.html"
    if request.method == "GET":
        return render(request, template_name, {"uidb64": uidb64, "token": token})

    else:
        try:
            user_email = urlsafe_base64_decode(uidb64).decode("utf-8")
            new_password = request.POST.get("password")
            if not isValidPassword(new_password):
                raise Exception("Invalid Password")
            token_generator = PasswordResetTokenGenerator()
        except Exception as e:
            print(e)
            messages.error(request, "Invalid Details")

user/templates/user/account.html
{% load static %}

<title>{{login_user.name}} Account</title>

<body>
    <!-- header part -->
    {% include "user/navbar.html" %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'user/css/account.css' %}">

    <script>
        function loadDefaultImage(default_img) {
            document.getElementById("profile_pic").src = default_img;
        }
    </script>

    {% if messages %}
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible shadow fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message | safe }}
    </div>
    {% endfor %}
    {% endif %}

    <!-- Left container part -->
    <div class="row container-fluid">
        <div class="Account-left container col">
            <!-- Area to upload user image (avatar) -->
            <div class="avatar-card">
                <div class="avatar-upload-area">
                    <form method="POST" action="{% url 'user:account' %}" enctype="multipart/form-data" onsubmit="return checkFileSize()">
                        {% csrf_token %}
                        {% if login_user.avatar %}
                        <img id="profile_pic" src="{{login_user.avatar.url}}" alt=""
                            onerror="loadDefaultImage('{% static 'user/images/default-avatar.png' %}')">
                        {% else %}
                        <img src="{% static 'user/images/default-avatar.png' %}" alt="Background Image">
                        {% endif %}
                        <!-- Upload button or input element -->
                        <label for="avatar-upload-input" class="avatar-upload-area-1">
                            <!-- Icon or text indicating upload action -->
                            <div class="upload-text">Upload Image</div>
                        </label>
                        <input type="file" name="avatar" id="avatar-upload-input" class="hidden-input" accept="image/*">
                    </form>
                </div>
            </div>

            <!-- name display part -->
            <div class="name-display container" style="display: flex; justify-content: space-between;align-items: baseline;">
                <span>{{login_user.name}}</span>
                <div>
                    <button id="summary_report" class='btn btn-primary'>Send Summary Report</button>
                    <button class='btn btn-success'><a href="{% url 'user:authorize_google_fit' %}" style="color: white;">Sign In using Google</a></button>
                </div>
            </div>

            <!-- user info -->
            <form id="user-info-form" method="POST" action="{% url 'user:account' %}">
                {% csrf_token %}
                <div class="user-info mx-5">
                    <div class="column">
                        <div class="row">
                            <div class="info-row">
                                <label class="info-label">Email</label>
                                <input type="text" name="email" class="info-field-disable" disabled
                                    value="{{ login_user.email }}">
                            </div>

                            <div class="info-row">
                                <label class="info-label">Name</label>
                                <input type="text" name="name" class="info-field" disabled
                                    value="{{ login_user.name }}">
                            </div>

                            <div class="info-row">
                                <label class="info-label">Phone</label>
                                <input type="text" name="phone" class="info-field" disabled
                                    value="{{ login_user.phone }}" oninput="formatPhoneNumber(this)">
                                <span id="phoneError" class="error-message"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="info-row">
                                <label class="info-label">City</label>
                                <input type="text" name="city" class="info-field" disabled value="{{ login_user.city }}">
                            </div>

                            <div class="info-row">
                                <label class="info-label">Gender</label>
                                <select class="info-field" id="sexSelect" name="sex" disabled>
                                    <option value="male">Male</option>
                                    <option value="female">Female</option>
                                    <option value="other">Other</option>
                                </select>
                            </div>

                            <div class="info-row">
                                <label class="info-label">City</label>
                                <input type="text" name="city" class="info-field" disabled value="{{ login_user.city }}">
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        </div>
</body>

<!-- some js code for user interaction -->
<script>
    // Borough selection part
    var userBorough = "{{ login_user.borough }}";
    var selectElement = document.getElementById("boroughSelect");

    var userSex = "{{ login_user.sex }}";
    var sexElement = document.getElementById("sexSelect");

    // Loop through options and set the default option based on user.borough
    for (var i = 0; i < selectElement.options.length; i++) {
        if (selectElement.options[i].value === userBorough) {
            selectElement.options[i].selected = true;
            break;
        }
    }

    // Loop through options and set the default option based on user.sex
    for (var i = 0; i < sexElement.options.length; i++) {
        if (sexElement.options[i].value === userSex) {
            sexElement.options[i].selected = true;
            break;
        }
    }
</script>
<script src="{% static 'user/javascript/account.js' %}"></script>

user/templates/user/dashboard.html
<h1>Dashboard Stuff</h1>

user/templates/user/login.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'user/css/login.css' %}">
<script src="{% static 'user/javascript/login.js' %}"></script>

{% if messages %}
  {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible shadow fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          {{ message | safe }}
      </div>
  {% endfor %}
{% endif %}
<div class="login-container">
  <div class="login-box">
    <h1>Welcome to <span>FitOn</span></h1>
    <form id="loginForm" method="post" action="{% url 'user:login' %}">
      {% csrf_token %}
      <div class="user-box">
        <input type="email" name="user_email" placeholder=" " required>
        <label>Email*</label>
      </div>
      <div class="user-box">
        <input type="password" name="user_pwd" placeholder=" " required>
        <label>Password*</label>
      </div>
      <button type="submit" id="btn_login_user">login</button>
    </form>
    <p>Forgot your credentials? <a href="{% url "user:passwordReset" %}">Recover here</a></p>
    <p>Don't have an account? <a href="{% url "user:user_registration" %}">Register here</a></p>
  </div>
</div>

user/templates/user/navbar.html
{% load static %}
<!DOCTYPE html>
<link rel="stylesheet" href="{% static 'user/css/navbar.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="header">
    <nav class="navbar justify-content-between my-0">
        <a class="text-decoration-none text-white" href={% url "user:home_dashboard" %}><span>FitOn</span></a>
        <form class="form-inline my-0">
            <a class='navbar_option' href="{% url "exercise:list_exercises" %}">Workouts</a>
            <a class='navbar_option' href="{% url "user:account" %}">Profile</a>
        </form>
    </nav>
</div>

user/templates/user/user_registration.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Registration Page</title>
<title>Registration Page</title>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'user/css/user_registration.css' %}">

<script src="{% static 'user/javascript/user_registration.js' %}"></script>

{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible shadow fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message | safe }}
</div>
{% endfor %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible shadow fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message | safe }}
</div>
{% endfor %}
{% endif %}

<div class="registration-container">
    <div class="registration-box" id="registration-box">
        <h1 class="text-center"><span>FitOn</span> User Registration</h1>
        <form id="registrationForm" method="POST" action="{% url "user:user_registration" %}">
            {% csrf_token %}
            <div id="user_details_section">
                <div class="form-group">
                    <input type="text" name="user_name" id="name" required placeholder=" ">
                    <label for="name">Name</label>
                </div>
                <div class="form-group">
                    <input type="email" name="user_email" id="email" required placeholder=" ">
                    <label for="email">Email</label>
                </div>
                <div class="form-group">
                    <label class="select-label" for="sex">Sex</label>
                    <select class="custom-select select-transparent" id="sex" name="user_sex" required>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                        <option value="other">Other</option>
                    </select>
                </div>
                <div class="form-group">
                    <input type="number" id="height" name="height" required placeholder=" ">
                    <label for="height">Height</label>
                    <select class="custom-select select-transparent" id="height_unit" name="height_unit">
                        <option value="cm">CM</option>
                        <option value="ft_in">FT/IN</option>
                    </select>
                    <div id="ftInFields" style="display: none;">
                        <input type="number" id="inches" name="inches" placeholder=" ">
                    </div>
                </div>
                <div class="form-group">
                    <input type="number" id="weight" name="weight" required placeholder=" ">
                    <label for="weight">Weight</label>
                    <select class="custom-select select-transparent" id="weight_unit" name="weight_unit">
                        <option value="kg">KG</option>
                        <option value="lb">LB</option>
                    </select>
                </div>
                <div class="form-group">
                    <input type="text" name="user_phone" id="phone" required oninput="formatPhoneNumber(this)">
                    <label for="phone">Phone Number</label>
                    <span id="phoneError" class="error-message"></span>
                </div>
                <div class="form-group">
                    <input type="text" id="city" name="city" placeholder=" " required>
                    <label for="city">City</label>
                </div>
    
                <button type="button" onclick="showPasswordFields()" id="continueButton">Continue</button>
                <p>Already have an account? <a href="{% url "user:login" %}" class="login">Login here</a></p>
            </div>
    
            <div class="hidden" id="passwordFields">
                <div class="form-group">
                    <input type="password" id="password" name="password" onkeyup="checkPassword()" placeholder=" ">
                    <label for="password">Password</label>
                </div>
                <div class="form-group">
                    <input type="password" id="confirm-password" onkeyup="checkPassword()" placeholder=" ">
                    <label for="confirm-password">Confirm Password</label>
                </div>
                <label id="password_status"> </label>
                <div class="form-group">
                    <button type="submit" disabled id="btn_register_user">Register</button>
                </div>
            </div>
    
        </form>
    </div>
</div>